services:
  email-api:
    container_name: email-api
    image: email-api
    build:
      context: ./api
      dockerfile: Dockerfile
    environment:
      PORT: ${API_PORT}
    ports:
      - "${API_PORT}:${API_PORT}"
    restart: always

  email-app:
    container_name: email-app
    image: email-app
    build:
      context: ./app
      dockerfile: Dockerfile
    environment:
      PORT: ${APP_PORT}
    ports:
      - "${APP_PORT}:${APP_PORT}"
    restart: always